logo: "/assets/images/IMG_7505_1-min.jpg"
title: "Itami Illustrations"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "neon"
url: "https://unclelukie.github.io"
baseurl: '/ItamiIllustrations'
repository: "uncleLukie/ItamiIllustrations"
plugins:
  - jekyll-include-cache

vendor_cache: vendor_cache.rb

author:
  name: "Kuragari Itami#1234"
  avatar: "/assets/images/itamiavatar.jpg"
  #image_alt: "Avatar of Kurugari Itami"
  bio: "I like turtles"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/itami_illustrations_/"
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://www.tiktok.com/@kuragari_itami"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/p7RfDcn"
    - label: "Paypal"
      icon: "fab fa-fw fa-paypal"
      url: "https://PayPal.me/KuragariItami"

social_links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/uncleLukie"

atom_feed:
  hide: true

footer: custom-footer.html
