logo: "/assets/images/fine-art-icon-14.png"
title: "Art By Itami"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "mint"
url: "https://unclelukie.github.io"
baseurl: '/ArtByItami'
repository: "uncleLukie/ArtByItami"
plugins:
  - jekyll-include-cache

vendor_cache: vendor_cache.rb


atom_feed:
  hide: true