logo: "/assets/images/fine-art-icon-14.png"
title: "Art By Itami"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "mint"
url: "https://unclelukie.github.io"
baseurl: '/ArtByItami'
repository: "uncleLukie/ArtByItami"

#author:
#  name: "Kurugari Itami"
#  bio: "Freelance artist creating beautiful illustrations and taking commissions"
#  avatar: "/assets/images/itamiavatar.jpg"
#  links:
#    - label: "Commissions"
#      icon: "fab fa-fw fa-paypal fa-beat"
#      url: "https://www.paypal.com/paypalme/mintlove108"
#    - label: "Discord"
#      icon: "fab fa-fw fa-discord"
#      url: "https://discordapp.com/users/813312536698290206"

atom_feed:
  hide: true